### ISSUE TITLE
Message list disappears, runtime error in console

### ISSUE THREAD

**Issue by Elwetana** [runbox/runbox7#323]
In Webmail, the list of messages disappears and will not reappear unless I refresh the page. In the console I can see repeatedly the following callstack:

```
Getting latest messages from server after Mon Oct 14 2019 18:08:41 GMT+0200 (Central European Summer Time)
main.0d2f865b3691f81adfb3.js:1 Failed updating with new changes (will retry in 10 secs) RuntimeError: memory access out of bounds
    at wasm-function[690]:16
    at wasm-function[1932]:15
    at Module.dynCall_iii (https://runbox.com/app/xapianasm.js:1:124680)
    at invoke_iii (https://runbox.com/app/xapianasm.js:1:107496)
    at wasm-function[1393]:46
    at wasm-function[1388]:62
    at wasm-function[3310]:244
    at wasm-function[1929]:17
    at Module.dynCall_iiii (https://runbox.com/app/xapianasm.js:1:124985)
    at invoke_iiii (https://runbox.com/app/xapianasm.js:1:108016)
```

The mailbox in question if fairly large (about 15 thousand). I'd be happy to provide more information.

**Comment by gtandersen** [comment]
@Elwetana To investigate this issue we need to know more about which account and server this is. 

Can you post the x-rmm-aliasid from the headers in a message in your Sent folder so that we can identify your Runbox account? (This ID is unique to each of your Runbox aliases and can only be mapped to your Runbox username by Runbox staff.)

**Comment by Elwetana** [comment]
Sure, no problem:

X-RMM-Aliasid: 776166

**Comment by Elwetana** [comment]
I can confirm that the problem still persists with the latest build:

Runbox 7 build time: 2020-01-17T15:32:57.210Z

**Comment by gtandersen** [comment]
@Elwetana Thanks for the follow-up. We have initiated a re-index of your account, which might resolve this problem.

**Comment by Elwetana** [comment]
@gtandersen Thank you. Unfortunately the problem is still present in both the latest version of Vivaldi (2.10) and Chrome (version 79.0). However, in Edge browser (the latest non-Chromium version) Runbox 7 works fine. I don't know you want to pursue a bug that's specific to Chromium browsers, but I'd be happy to share more information if you need it.

I have tested it on my own computer, cleared cache and storage and also tried it on a completely new computer, but the result was always the same.

**Comment by gtandersen** [comment]
@Elwetana Can you try opening the URL that generates the error in the web console? 

It is probably of the type `https://runbox.com/mail/download_xapian_index` with some parameters at the end.

You should be able to right-click the URL in your console and open it in a new tab.

**Comment by Elwetana** [comment]
I can open that URL and it contains some minimized JS code, what do you want me to do with that?

I am attaching a complete console log from the moment I start to load the page, to the moment when the error appears (line 43866). The actual callstack still looks the same -- see my original post. The last two lines are:

    at Module.dynCall_iiii (https://runbox.com/app/xapianasm.js:1:124985)
    at invoke_iiii (https://runbox.com/app/xapianasm.js:1:108016)

I can open https://runbox.com/app/xapianasm.js, that does not seem to be a problem. I'd be very happy to provide more information, please let me know what you need.

[runbox.com-1581594970354.log](https://github.com/runbox/runbox7/files/4199015/runbox.com-1581594970354.log)

**Comment by gtandersen** [comment]
This is probably related to https://github.com/runbox/runbox7/issues/713.

**Comment by gtandersen** [comment]
We have made several improvements to the message list and index synchronization since this was reported. 

Is the issue still occurring @Elwetana?
